# For a detailed explanation regarding each configuration property, visit:
# https://jestjs.io/docs/configuration

clearMocks: true
collectCoverage: true
coverageDirectory: 'coverage'
coverageProvider: 'v8'

# coverageReporters:
#   - "json"
#   - "text"
#   - "lcov"
#   - "clover"

# coverageThreshold: undefined

# globalSetup: undefined
# globalTeardown: undefined

# globals: {}

# maxWorkers: "50%"

# moduleDirectories:
#   - "node_modules"

# moduleFileExtensions:
#   - "js"
#   - "mjs"
#   - "cjs"
#   - "jsx"
#   - "ts"
#   - "tsx"
#   - "json"
#   - "node"

# moduleNameMapper: {}

# modulePathIgnorePatterns: []

# notify: false
# notifyMode: "failure-change"

# preset: undefined
# projects: undefined
# reporters: undefined

# resetMocks: false
# resetModules: false
# resolver: undefined
# restoreMocks: false

# rootDir: undefined
# roots:
#   - "<rootDir>"

# runner: "jest-runner"
# setupFiles: []
# setupFilesAfterEnv: []

# slowTestThreshold: 5
# snapshotSerializers: []

# testEnvironment: "jest-environment-node"
# testEnvironmentOptions: {}

# testLocationInResults: false

# testMatch:
#   - "**/__tests__/**/*.[jt]s?(x)"
#   - "**/?(*.)+(spec|test).[tj]s?(x)"

# testPathIgnorePatterns:
#   - "/node_modules/"

# testRegex: []
# testResultsProcessor: undefined
# testRunner: "jest-circus/runner"

# transform: undefined
# transformIgnorePatterns:
#   - "/node_modules/"
#   - "\\.pnp\\.[^\\/]+$"

# unmockedModulePathPatterns: undefined

verbose: true
