name: Deply Project
on: [push, workflow_dispatch] #This workflow will run on push and manual trigger
# env:
#     NODE_ENV: 'production'
jobs:
    lint:
        env:
            NODE_ENV: 'development'
        name: 🧹 Lint
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Use Node.js 23.x
              uses: actions/setup-node@v4
              with:
                  node-version: 23.x
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
            - name: Lint code
              run: npm run lint
            - name: Output information
              run: 'echo NODE_ENV: ${{env.NODE_ENV}}'
    test:
        name: 🧪 Tests (Unit)
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Use Node.js 23.x
              uses: actions/setup-node@v4
              with:
                  node-version: 23.x
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
    build:
        runs-on: ubuntu-latest
        needs: [test, lint] #This job depends on the test job - it will only run if the test job is successful
        outputs:
            dist: ${{ steps.publish.outputs.dist_files }}
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Use Node.js 23.x
              uses: actions/setup-node@v4
              with:
                  node-version: 23.x
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Publish JS filename
              id: publish
              run: find dist/*.js -type f -execdir echo 'dist_files={}' >> $GITHUB_OUTPUT ';'
              # run: find dist/*.js -type f -execdir echo '::set-output name=dist_files::{}' ';' - Same but another sintax

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist-files
                  path: | #This is a multi-line string
                      dist
                      package.json
    deploy:
        runs-on: ubuntu-latest
        needs: [build] #This job depends on the test job - it will only run if the test job is successful
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: dist-files
            - name: Display structure of downloaded files
              run: ls -R dist
            - name: Output filename
              run: echo ${{ needs.build.outputs.dist }}
