name: Deply Project
on: [push, workflow_dispatch] #This workflow will run on push and manual trigger
jobs:
    lint:
        name: 🧹 Lint
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Use Node.js 23.x
              uses: actions/setup-node@v4
              with:
                  node-version: 23.x
            - name: Install dependencies
              run: npm ci
            - name: Lint code
              run: npm run lint
    test:
        name: 🧪 Tests (Unit)
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Use Node.js 23.x
              uses: actions/setup-node@v4
              with:
                  node-version: 23.x
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
    build:
        runs-on: ubuntu-latest
        needs: [test, lint] #This job depends on the test job - it will only run if the test job is successful
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Use Node.js 23.x
              uses: actions/setup-node@v4
              with:
                  node-version: 23.x
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist-files
                  path: | #This is a multi-line string
                      dist
                      package.json
    deploy:
        runs-on: ubuntu-latest
        needs: [test, lint] #This job depends on the test job - it will only run if the test job is successful
        steps:
            - name: Deploy
              run: echo "Deploying ..."
