name: Issue Event
on: issues
jobs:
    show-issue:
        runs-on: ubuntu-latest
        steps:
            - name: Show issue
              run: 'echo "Issue title: ${{ github.event.issue.title }}"''