name: Reusable Deploy
on: workflow_call # Allows to trigger the workflow from another workflow
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Deploy project
              run: echo "Deploying project from reusable workflow ..."
