name: Test Project
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v2
            - name: Use Node.js 23.x
              uses: actions/setup-node@v2
              with:
                  node-version: 23.x
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test
